version: "3.1"

services:
  amnesty_db:
    image: postgres:9.6
    volumes:
      - "amnesty_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
  amnesty_pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - amnesty_pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - amnesty_db

volumes:
  amnesty_db_data:
  amnesty_pgadmin:
